### ISSUE TITLE
how to catch events?

### ISSUE THREAD

**Issue by maxmasetti** [burzum/cakephp-user-tools#39]
I cant understand why you can't catch the event in the controller event manager but in the global yes.
```
  public function initialize()
  {
    parent::initialize();
    $this->loadComponent('Burzum/UserTools.UserTool');

    EventManager::instance()->on('User.beforeLogin', function ($event) {
      $event->stopPropagation();
      return false;
      // WORKS!
    });

    $this->eventManager()->on('User.beforeLogin', function ($event) {
      $event->stopPropagation();
      return false;
      // DOESN'T WORK
    });

  }
```
thanks

**Comment by burzum** [comment]
The behaviour is correct. The event is not attached to the controllers event manager.

See https://github.com/burzum/cakephp-user-tools/blob/master/src/Controller/Component/UserToolComponent.php#L25

And see http://api.cakephp.org/3.3/source-class-Cake.Event.EventDispatcherTrait.html#1

But I think it might be a good idea to re-use the controllers event manager instead of creating a new instance inside the component. I'll check this out and make a change to the plugin.
